version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/urlshortener
      - REDIS_HOST=redis
      - BASE_URL=http://localhost:3000
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
